-- Enums in SQLite are typically handled via CHECK constraints or just TEXT columns
-- We'll use TEXT for simplicity and application-level validation.

CREATE TABLE IF NOT EXISTS tenants (
  id TEXT PRIMARY KEY, -- We'll generate UUIDs in the app or use hex strings
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  logo_url TEXT,
  active INTEGER DEFAULT 1, -- boolean
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY, -- This will be the user's ID
  tenant_id TEXT,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'user', -- 'super_admin', 'admin', 'user'
  status TEXT DEFAULT 'pending', -- 'pending', 'active', 'suspended'
  push_subscription TEXT, -- Store JSON as TEXT
  push_enabled INTEGER DEFAULT 0, -- boolean
  language TEXT DEFAULT 'es',
  theme TEXT DEFAULT 'light',
  company_name TEXT,
  email TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS work_orders (
  id TEXT PRIMARY KEY,
  order_number INTEGER,
  tenant_id TEXT NOT NULL,
  created_by TEXT,
  titulo TEXT NOT NULL,
  descripcion TEXT,
  prioridad TEXT DEFAULT 'media', -- 'baja', 'media', 'alta', 'urgente'
  ubicacion TEXT,
  categoria TEXT DEFAULT 'otro', -- 'electrico', 'plomeria', 'climatizacion', 'estructural', etc.
  asignado_a TEXT,
  estado TEXT DEFAULT 'pendiente', -- 'pendiente', 'en-pausa', 'completada'
  file_url TEXT,
  file_name TEXT,
  attachments TEXT DEFAULT '[]', -- Store JSON as TEXT
  fecha_programada DATE,
  observaciones TEXT,
  deleted INTEGER DEFAULT 0, -- boolean
  deleted_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL
);

-- Note: In SQLite, you cannot have another PRIMARY KEY if you use INTEGER PRIMARY KEY AUTOINCREMENT
-- So we need to refactor work_orders slightly if we want both a UUID 'id' and an auto-incrementing 'order_number'.
-- Let's fix that.

DROP TABLE IF EXISTS work_orders;
CREATE TABLE IF NOT EXISTS work_orders (
  id TEXT PRIMARY KEY, -- UUID generated by app
  order_number INTEGER, -- We'll manually increment this or handle it in the app logic
  tenant_id TEXT NOT NULL,
  created_by TEXT,
  titulo TEXT NOT NULL,
  descripcion TEXT,
  prioridad TEXT DEFAULT 'media',
  ubicacion TEXT,
  categoria TEXT DEFAULT 'otro',
  asignado_a TEXT,
  estado TEXT DEFAULT 'pendiente',
  file_url TEXT,
  file_name TEXT,
  attachments TEXT DEFAULT '[]',
  fecha_programada DATE,
  observaciones TEXT,
  deleted INTEGER DEFAULT 0,
  deleted_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS work_order_history (
  id TEXT PRIMARY KEY,
  work_order_id TEXT NOT NULL,
  tenant_id TEXT NOT NULL,
  user_id TEXT,
  user_name TEXT,
  event_type TEXT NOT NULL, -- 'created', 'status_changed', 'updated', 'deleted', 'restored'
  old_status TEXT,
  new_status TEXT,
  note TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL
);

-- Default initial data
INSERT OR IGNORE INTO tenants (id, name, slug) VALUES ('00000000-0000-0000-0000-000000000000', 'Sistema Principal', 'sistema-principal');
